# Generated by Django 3.2.9 on 2021-11-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priorties',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Managers',
            new_name='Manager',
        ),
        migrations.RenameModel(
            old_name='ReportingMethods',
            new_name='Priority',
        ),
        migrations.RenameModel(
            old_name='Reporters',
            new_name='Reporter',
        ),
        migrations.RenameModel(
            old_name='Subcategories',
            new_name='ReportingMethod',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Subcategory',
        ),
    ]
