# Generated by Django 3.2.9 on 2021-11-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211107_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_set', to='base.branch'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.priority'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reporting_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.reportingmethod'),
        ),
        migrations.AlterField(
            model_name='case',
            name='subcategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subcategory'),
        ),
    ]
