# Generated by Django 3.2.9 on 2021-11-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211107_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.branch'),
        ),
    ]
