# Generated by Django 3.2.9 on 2021-11-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_case_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='base.branch'),
        ),
    ]
